repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
        args: ["--py36-plus"]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.0
    hooks:
    -   id: pyupgrade
        args: ["--py38-plus"]
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
